# Generated by Django 5.2.12 on 2026-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaFranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Zona Franca')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(default='Costa Rica', max_length=100, verbose_name='País')),
                ('imagen', models.URLField(blank=True, null=True, verbose_name='URL de Imagen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categorias', models.JSONField(default=list, verbose_name='Categorías')),
                ('activa', models.BooleanField(default=True, verbose_name='Zona Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Zona Franca',
                'verbose_name_plural': 'Zonas Francas',
                'ordering': ['nombre'],
            },
        ),
    ]
