# Generated by Django 5.2.12 on 2026-03-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Institución')),
                ('tipo', models.CharField(choices=[('Colegio', 'Colegio'), ('Universidad', 'Universidad'), ('Técnico', 'Técnico')], max_length=20, verbose_name='Tipo de Institución')),
                ('cedula_juridica', models.CharField(max_length=20, unique=True, verbose_name='Cédula Jurídica')),
                ('nombre_responsable', models.CharField(max_length=255, verbose_name='Nombre del Contacto Responsable')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de Contacto')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Institucional')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección (Provincia/Cantón)')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
